### ISSUE TITLE
Useful features

### ISSUE THREAD

**Issue by slice** [lnmds/cubix#17]
I really, really, really like this software.

Could you add these, please?

- [ ] Litecord integration
- [ ] x86 emulation
  - [ ] 64-bits support
- [ ] Arch Linux but it uses YAPI

**Comment by slice** [comment]
Please answer my question above
I'd like to fork it and make copies

**Comment by slice** [comment]
I know a couple people online that would love it, please reply

**Comment by slice** [comment]
I really, really, really, like this software.

**Comment by slice** [comment]
I'm glad that I suggest something to you
Sometimes dreams can come true
I'm happy that I could have a GitHub issue with you

**Comment by lnmds** [comment]
On the internet.

**Comment by Mstrodl** [comment]
You're right it is super great. Thanks for stopping bye
