### ISSUE TITLE
OUR FREE SPEECH IS BEINGG VIOLATED

### ISSUE THREAD

**Issue by slice** [lnmds/cubix#23]
![](https://owo.sh/4bab5f.png)

@lnmds @Mstrodl

**Comment by Mstrodl** [comment]
STOP HARASSING ME

**Comment by Mstrodl** [comment]
CALLING 711 RIGHT NOW

**Comment by slice** [comment]
I CAN'T STOp

**Comment by lnmds** [comment]
shitposting is quite good i like it
